# Generated by Django 3.1.2 on 2020-12-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_courses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
