# Generated by Django 3.1.2 on 2021-01-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_auto_20201230_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institutegroup',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pathwaygroup',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
