# Generated by Django 3.1.2 on 2021-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_auto_20210101_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreelevel',
            name='level_type',
            field=models.CharField(choices=[('undergradute', 'Undergradute'), ('postgradute', 'Postgradute'), ('postgradute_by_research', 'Postgradute by Research')], default='undergradute', max_length=50),
        ),
    ]
