# Generated by Django 3.1.2 on 2021-03-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_degreelevel_level_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Apply portal short Name key', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='Apply Portal Name', max_length=255)),
                ('description', models.TextField(help_text=' Apply portal content')),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='apply_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.applyportal'),
        ),
    ]
