# Generated by Django 3.1.2 on 2021-03-02 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0005_auto_20210301_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='apply_portal',
        ),
        migrations.AddField(
            model_name='institute',
            name='apply_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructor.applyportal'),
        ),
    ]
