# Generated by Django 3.1.2 on 2021-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_auto_20210302_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
