# Generated by Django 3.1.4 on 2021-03-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_discipline_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyportal',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='degreelevel',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discipline',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='institutegroup',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pathwaygroup',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
