# Generated by Django 3.1.2 on 2021-04-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0013_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='institute_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
