# Generated by Django 3.1.2 on 2021-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0015_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='institute_short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instituteranking',
            name='ranking_type',
            field=models.CharField(choices=[('qs_world_ranking', ' QS World University Rankings'), ('times_higher_world_ranking', 'Times Higher Education World University Rankings'), ('us_news_world_ranking', 'US News Global Universities Rankings'), ('shanghai_ranking', 'Shanghai Rankings'), ('us_news_national_ranking', 'Shanghai Rankings'), ('tcf_ranking', 'TCF Rankings')], max_length=100),
        ),
    ]
