# Generated by Django 3.1.2 on 2021-04-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0016_auto_20210419_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyportal',
            name='short_description',
            field=models.TextField(default='description', help_text=' Group content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institutegroup',
            name='short_description',
            field=models.TextField(default='description', help_text=' Group content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pathwaygroup',
            name='short_description',
            field=models.TextField(default='description', help_text=' Group content'),
            preserve_default=False,
        ),
    ]
