# Generated by Django 3.1.2 on 2021-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0018_dynamicpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_description',
            field=models.TextField(default='description', help_text=' Country content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicpages',
            name='type',
            field=models.CharField(choices=[('privacy', 'Privacy Notice'), ('terms', 'Terms & Conditions'), ('tcf_intro', 'About TCF'), ('Careers', 'Careers'), ('contact', 'Contact Us'), ('marketing_advertisement', 'Marketing & Advertisement'), ('english_program_in_europe', 'English Program in Europe'), ('cheapest_MBA', 'Cheapest MBA'), ('suitable_program_in_uni', 'How to find suitable program in University')], max_length=50, unique=True),
        ),
    ]
