# Generated by Django 3.1.2 on 2021-04-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0019_auto_20210426_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='short_description',
            field=models.TextField(blank=True, help_text=' Country content', null=True),
        ),
    ]
