# Generated by Django 3.1.2 on 2021-05-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0020_auto_20210430_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapply',
            name='url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
