# Generated by Django 3.1.2 on 2021-05-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0021_auto_20210508_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.state'),
        ),
        migrations.AlterField(
            model_name='instituteacceptingratio',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.institute'),
        ),
        migrations.AlterField(
            model_name='institutecampus',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.city'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.country'),
        ),
        migrations.AlterField(
            model_name='subdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.discipline'),
        ),
    ]
