# Generated by Django 3.1.2 on 2021-05-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0022_auto_20210520_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='short_description',
            field=models.TextField(default='test', help_text=' Group content'),
            preserve_default=False,
        ),
    ]
