# Generated by Django 3.1.2 on 2021-05-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0026_auto_20210531_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshiporganization',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constructor.country'),
            preserve_default=False,
        ),
    ]
