# Generated by Django 3.1.2 on 2021-05-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0027_scholarshiporganization_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='Institute_name_organizational_scholarship',
            new_name='institute_name_organizational_scholarship',
        ),
    ]
