# Generated by Django 3.1.2 on 2021-06-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0030_country_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='Region',
            new_name='region',
        ),
    ]
