# Generated by Django 3.1.2 on 2021-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0034_auto_20210708_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='base_fee',
            field=models.FloatField(default=0),
        ),
    ]
