# Generated by Django 3.1.2 on 2021-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0035_course_base_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(default='add name from admin', help_text='Australian Dollar (AUD)', max_length=255),
            preserve_default=False,
        ),
    ]
