# Generated by Django 3.1.2 on 2021-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0036_currency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='career_prospects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='structure',
            field=models.TextField(blank=True, null=True),
        ),
    ]
