# Generated by Django 3.1.2 on 2021-09-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0038_auto_20210824_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpages',
            name='type',
        ),
    ]
