# Generated by Django 3.1.2 on 2021-09-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0039_remove_dynamicpages_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_type', models.CharField(choices=[('image_card', 'Image Card'), ('content_card', 'Content  Card')], default='content_card', max_length=50)),
                ('name', models.CharField(help_text='Card Name', max_length=255, verbose_name='Name')),
                ('heading', models.CharField(help_text='Card heading', max_length=255, verbose_name='heading')),
                ('short_description', models.CharField(max_length=1000)),
                ('content', models.TextField(help_text='content', verbose_name='content')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
