# Generated by Django 3.1.2 on 2021-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0040_marketingcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcard',
            name='card_img',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
    ]
