# Generated by Django 3.1.2 on 2021-10-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0041_marketingcard_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='scholarship_logo',
            field=models.URLField(blank=True, max_length=700, null=True),
        ),
    ]
