# Generated by Django 3.1.2 on 2021-10-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0042_country_scholarship_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_name',
            field=models.CharField(help_text='Scholarship name', max_length=500),
        ),
    ]
