# Generated by Django 3.1.2 on 2021-10-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0043_auto_20211012_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshiporganization',
            name='name',
            field=models.CharField(help_text='Scholarship name', max_length=750),
        ),
    ]
