# Generated by Django 3.1.2 on 2021-10-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0044_auto_20211012_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title', max_length=255, verbose_name='Title')),
                ('category', models.CharField(choices=[('home', 'Home'), ('scholarship', 'Scholarship'), ('compare', 'Course compare'), ('apply', 'Course apply'), ('discover', 'Discover'), ('university-groups', 'University Groups'), ('contact-us', 'Contact Us'), ('careers', 'Careers'), ('about', 'About'), ('marketing', 'Marketing'), ('privacy', 'Privacy'), ('terms_and_use', 'Terms and Use')], max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
