# Generated by Django 3.1.2 on 2021-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0045_seocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.FloatField(blank=True, help_text='latitude', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.FloatField(blank=True, help_text='longitude', null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='latitude',
            field=models.FloatField(blank=True, help_text='latitude', null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='longitude',
            field=models.FloatField(blank=True, help_text='longitude', null=True),
        ),
    ]
