# Generated by Django 3.1.2 on 2022-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0046_auto_20211108_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcard',
            old_name='card_img',
            new_name='card_img_back',
        ),
        migrations.AddField(
            model_name='marketingcard',
            name='card_img_detail',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
        migrations.AddField(
            model_name='marketingcard',
            name='card_img_front',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
    ]
