# Generated by Django 3.1.2 on 2022-02-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0047_auto_20220110_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcard',
            name='list_card_img_back',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
        migrations.AddField(
            model_name='marketingcard',
            name='list_card_img_detail',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
        migrations.AddField(
            model_name='marketingcard',
            name='list_card_img_front',
            field=models.ImageField(blank=True, null=True, upload_to='marketing/images'),
        ),
        migrations.AddField(
            model_name='marketingcard',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
