# Generated by Django 3.1.2 on 2022-02-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0048_auto_20220211_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbbreviationElaborationWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elaboration_word', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbbreviationWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abbreviation_word', models.CharField(max_length=7)),
                ('elaboration_words', models.ManyToManyField(to='constructor.AbbreviationElaborationWord')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
