# Generated by Django 3.1.2 on 2022-03-08 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0049_abbreviationelaborationword_abbreviationword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcard',
            name='short_description',
        ),
    ]
