# Generated by Django 3.1.2 on 2022-03-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0050_remove_marketingcard_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingcard',
            old_name='card_img_back',
            new_name='detail_page_img',
        ),
        migrations.RenameField(
            model_name='marketingcard',
            old_name='card_img_detail',
            new_name='grid_card_img_back',
        ),
        migrations.RenameField(
            model_name='marketingcard',
            old_name='card_img_front',
            new_name='grid_card_img_front',
        ),
        migrations.RemoveField(
            model_name='marketingcard',
            name='list_card_img_detail',
        ),
    ]
