# Generated by Django 3.1.14 on 2022-03-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0051_auto_20220308_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopQueryWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('words_list', models.JSONField()),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
