# Generated by Django 3.1.14 on 2022-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0052_stopqueryword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopqueryword',
            name='words_list',
        ),
        migrations.AddField(
            model_name='stopqueryword',
            name='stop_word',
            field=models.CharField(default='test', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
