# Generated by Django 3.1.14 on 2022-03-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0053_auto_20220311_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
