# Generated by Django 3.1.2 on 2022-03-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0054_shorturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesDetailsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Title', max_length=255, null=True, verbose_name='Title')),
                ('category', models.CharField(choices=[('all-groups', 'All Groups'), ('all-countries', 'All Countries'), ('all-programs', 'All Programs'), ('all-scholarships', 'All Scholarships'), ('scholarship-country', 'Scholarship Country'), ('all-apply-portals', 'All Apply Portals')], max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'get_latest_by': 'updated_at',
                'abstract': False,
            },
        ),
    ]
