# Generated by Django 3.2 on 2022-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0055_pagesdetailscontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='base_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
